### ISSUE TITLE
local mqtt

### ISSUE THREAD

**Issue by disaster123** [micw/tibber-pulse-reader#19]
i can't get local mqtt working. If i try to delete the certs - they got filles with the words: cert, private_key, ... and it connects to my mqtt but disconnects immediatly...

**Comment by micw** [comment]
Please give more context ;)

**Comment by disaster123** [comment]
*argh* wrong repo - wanted to place it here: https://github.com/MSkjel/LocalPulse2Tibber

**Comment by micw** [comment]
Makes sense ;-) Good luck.
