### ISSUE TITLE
Container fails to start if PUBLISH_FILTERS is missing

### ISSUE THREAD

**Issue by JMyrng** [micw/tibber-pulse-reader#3]
At first: nice work, container works like a charm!

I'm running it on x86 with Portainer. 

Now to the _small_ problem: 
the container fails to start if there is no `PUBLISH_FILTERS ` environment variable. 

I've now set it to `"1-0:2.8.0*255=IGNORE"` and it works.

Best regards,
Jonas

**Comment by micw** [comment]
Should work now

**Comment by JMyrng** [comment]
Perfect! Thanks.
