### ISSUE TITLE
SML parsing error

### ISSUE THREAD

**Issue by xemax343** [micw/tibber-pulse-reader#5]
Ok, dann hier nochmal neu:

`2023-03-18 17:27:21.115 DEBUG 1 --- [           main] de.wyraz.tibberpulse.sml.SMLDecoder      : Parsing SML: 1b1b1b1b0101010176040000016200620072650000010176010107000005e370330b0a01484c59020005dc4b010163d7210076040000026200620072650000070177010b0a01484c59020005dc4b01017c77070100603201010101010104484c590177070100600100ff010101010b0a01484c59020005dc4b0177070100010800ff65000000046505e37033621e52ff6504c2bfcc0177070100020800ff65000000046505e37033621e52ff65002d3d840177070100100700ff0101621b520052000177070100200700ff0101622352ff63090301770701001f0700ff0101622152fe62000177070100510704ff010162085200620001770701000e0700ff0101622c52ff6301f30177070100000200000101010109322e30312e3030310177070100605a02010101010105303246340177070100600500ff01010101650000000401010163682f00760400000362006200726500000201710163e8230000001b1b1b1b1a021af2`
`2023-03-18 17:27:21.168  WARN 1 --- [           main] d.w.t.source.TibberPulseHttpReader       : Unable to parse SML from response`

Ja, könnte am Decoder liegen. Bei Tasmota hatte ich auch eine Weile gebraucht, bis das funktionierte.

**Comment by micw** [comment]
Ich hab das ganze mal debuggt. Wenn der Parser soweit korrekt funktioniert, kommt es irgendwann zu einem Feld "SML Time", dessen "Choice" als 32 bit unsigned codiert ist. Laut der Spec darf hier nur 8 bit unsigned verwendet werden.

https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03109/TR-03109-1_Anlage_Feinspezifikation_Drahtgebundene_LMN-Schnittstelle_Teilb.pdf?__blob=publicationFile&v=1

in 6.3.3
(145) Elemente vom Typ SML_MessageBody kodieren das TAG als Unsigned32, alle anderen
als Unsigned8.

Ich vermute mal, dass hier ein Fehler im Zähler vorliegt.

**Comment by micw** [comment]
Schick mal noch ein zweites Paket zum Abgleich.

**Comment by micw** [comment]
Und was genau war bei Tasmota da nötig?

**Comment by xemax343** [comment]
Bei Tasmota kann man verschiedene Zähler wählen, da die wohl Unterschiedlich viele Daten senden.

Hier noch eine SML Nachricht
`1b1b1b1b0101010176040000016200620072650000010176010107000005e390e60b0a01484c59020005dc4b010163fc560076040000026200620072650000070177010b0a01484c59020005dc4b01017c77070100603201010101010104484c590177070100600100ff010101010b0a01484c59020005dc4b0177070100010800ff65000000046505e390e6621e52ff6504c2bfcc0177070100020800ff65000000046505e390e6621e52ff65002d3d840177070100100700ff0101621b520052000177070100200700ff0101622352ff63090b01770701001f0700ff0101622152fe62000177070100510704ff010162085200620001770701000e0700ff0101622c52ff6301f40177070100000200000101010109322e30312e3030310177070100605a02010101010105303246340177070100600500ff01010101650000000401010163a2fd00760400000362006200726500000201710163e8230000001b1b1b1b1a02c734`

**Comment by xemax343** [comment]
Hab das mal bei Tasmota parsen lassen
[https://tasmota-sml-parser.dicp.net](https://tasmota-sml-parser.dicp.net/)
Auf der Seite folgendes reinkopieren:
1b 1b 1b 1b 01 01 01 01 76 04 00 00 01 62 00 62 00
72 65 00 00 01 01 76 01 01 07 00 00 05 e3 93 3c 0b 0a 01 48 4c 59 02 00 05 dc 4b 01 01 63 53 8f 00 76 04 00 00 02 62 00
62 00 72 65 00 00 07 01
77 01 0b 0a 01 48 4c 59 02 00 05 dc 4b 01 01 7c
77 07 01 00 60 32 01 01 01 01 01 01 04 48 4c 59 01
77 07 01 00 60 01 00 ff 01 01 01 01 0b 0a 01 48 4c 59 02 00 05 dc 4b 01
77 07 01 00 01 08 00 ff 65 00 00 00 04 65 05 e3 93 3c 62 1e 52 ff 65 04 c2 bf cc 01
77 07 01 00 02 08 00 ff 65 00 00 00 04 65 05 e3 93 3c 62 1e 52 ff 65 00 2d 3d 84 01
77 07 01 00 10 07 00 ff 01 01 62 1b 52 00 52 00 01
77 07 01 00 20 07 00 ff 01 01 62 23 52 ff 63 09 15 01
77 07 01 00 1f 07 00 ff 01 01 62 21 52 fe 62 00 01
77 07 01 00 51 07 04 ff 01 01 62 08 52 00 62 00 01
77 07 01 00 0e 07 00 ff 01 01 62 2c 52 ff 63 01 f4 01
77 07 01 00 00 02 00 00 01 01 01 01 09 32 2e 30 31 2e 30 30 31 01
77 07 01 00 60 5a 02 01 01 01 01 01 05 30 32 46 34 01
77 07 01 00 60 05 00 ff 01 01 01 01 65 00 00 00 04 01 01 01 63 fa
77 00 76 04 00 00 03 62 00 62 00 72 65 00 00 02 01 71 01 63 e8 23 00 00 00 1b 1b 1b 1b 1a 02 00 a3

Ich brauche eigentlich nur diese 3 Werte
`77070100010800FF@1,Zählerstand Total,Wh,zählerstand_total,1`
`77070100020800FF@1,Wirkenergie Total,Wh,wirkenergie_total,1`
`77070100100700FF@1,aktuelle Wirkleistung,W,aktuelle_wirkleistung,0`

**Comment by micw** [comment]
So einfach isses leider nicht, der Parser vom Fraunhofer steigt da einfach aus und man kann nix machen.

Ich habe jetzt doch mal nach BSI TR-03109-1 einen Parser implementiert. Dann habe ich auch mehr Kontrolle und sehe, was genau schief geht. Für den Zähler habe ich einen Workaround implementiert, nun kommt folgendes raus:

Meter 1HLY0200384075
 1-0:1.8.0*255 / energyImportTotal = 7987194.8 WATT_HOUR
 1-0:2.8.0*255 / energyExportTotal = 296486.8 WATT_HOUR
 1-0:16.7.0*255 / powerTotal = 0 WATT
 1-0:32.7.0*255 / voltageL1 = 230.7 VOLT
 1-0:31.7.0*255 / currentL1 = 0.00 AMPERE
 1-0:81.7.4*255 / phaseAngleIL1toUL1 = 0 DEGREE
 1-0:14.7.0*255 / networkFrequency = 49.9 HERTZ

schau mal drüber, ob das plausibel ist. Komisch, dass Strom und Leistung null sind.

**Comment by micw** [comment]
Neuer Parser implementiert noch nicht 100% vom standard. Es laufen aber alle Tests, daher liegt's jetzt im Git.
Viel Spaß beim Testen

**Comment by xemax343** [comment]
Ich habe eine Solaranlage, daher die 0 Watt und 0 A Strom zur Zeit.
Funktioniert ohne Probleme. Vielen Dank!

**Comment by micw** [comment]
Super. Schick doch bitte noch ein Bild vom Zähler und/oder den genauen Zählertyp. Ich würde gerne eine Doku aufbauen, welche Zähler welche Workarounds benötigen.
Hab mit eben mal libsml vom "Volkszähler" angeschaut, die haben den gleichen Workaround für den Zähler eines anderen Herstellers.

**Comment by xemax343** [comment]
Das ist ein Holley DDZ285-ZEBA.

**Comment by paschdan** [comment]
hui ich drück mal die daumen, das die LED beim holley durchhält :)

**Comment by micw** [comment]
> hui ich drück mal die daumen, das die Diode beim holley durchhält :)

Ich verstehe die Aussage nicht ...

**Comment by micw** [comment]
BTW: ich mache gerade ein Hardware-Projekt, das Signal vom Zähler zu kopieren, so dass man den Tibber und eigene Hardware (USB, Lesekopf oder ESP8266) anschließen kann. Damit wäre das Auslesen komplett unabhängig vom Tibber möglich.

**Comment by mslookup** [comment]
Falls du dein "Hardwareprojekt" verkaufen würdest, ich würde eines nehmen ;)

**Comment by micw** [comment]
Gern, dauert aber noch ein paar Wochen (Test mit Pulse, Bestellung Platinen). Ich bestelle einen Schwung und verschicke gerne ein paar. Basis-Lötkenntnisse sind benötigt (LED + Stecker einlöten)

**Comment by paschdan** [comment]
> > hui ich drück mal die daumen, das die Diode beim holley durchhält :)
> 
> Ich verstehe die Aussage nicht ...

Die Holleys sind bekannt dafür nach 3-4 Jahren den Geist aufzugeben an der optischen Schnittstelle. Meiner ging schon nach 1 Jahr nicht mehr, habe jetzt nen anderen Anderen Hersteller, und hoffe das ding hält länger durch

**Comment by mark82436** [comment]
Ich würde mich auch gerne dem Hardwareprojekt anschließen, da ich einen Hichi und einen Pulse betreiben möchte.
Gib einfach Bescheid, wenn es so weit ist.

**Comment by mslookup** [comment]
Ich würde vorschlagen: Lasst uns das Thema "Gleichzeitige Verwendung von mehreren Leseköpfen" in Issue 7 weiter diskutieren, damit das ursprüngliche Thema hier in diesem Issue fortgeführt und irgendwann auch geschlossen werden kann.

https://github.com/micw/tibber-pulse-reader/issues/7

**Comment by micw** [comment]
Alles klar, dann mach ich hier zu.
