### ISSUE TITLE
Gleichzeitige Verwendung von mehreren Leseköpfen an IR Schnittstelle

### ISSUE THREAD

**Issue by mslookup** [micw/tibber-pulse-reader#7]
Hallo zusammen,

in Issue #5 hat sich eine kleine Diskussion hinsichtlich des gleichzeitigen Betriebes von mehreren Leseköpfen entwickelt. 
Da bereits mehrere Wortbeiträge existieren und das eigentliche Thema in dem ursprünglichen Issue ein anderes ist, habe ich gedacht, wir starten hier ein neues Issue und haben damit einen Platz, und ausgiebig über das Thema zu unterhalten.

Ich selbst habe auch bereits meine Erfahrungen gemacht und würde die ebenfalls gerne mit euch teilen.

**Comment by micw** [comment]
@mslookup ich habe im Projekt Diskussionen aktiviert. Würdest Du dort eine starten und das Ticket zumachen?

**Comment by mslookup** [comment]
Fortführung hier: https://github.com/micw/tibber-pulse-reader/discussions/8
